backend:
  name: github
  branch: netlify
  repo: autogram-is/goingresponsive

media_folder: '_src/chapter/image/'
public_folder: '/chapter/image'

collections:
  - name: 'pages'
    label: 'Pages'
    files: 
      - label: 'Homepage'
        name: 'home'
        file: '_src/index.md'
        editor:
          preview: false
        fields:
          - { label: 'Heading', name: 'title', widget: 'string', required: false  }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'chapter'
    label: 'Chapters'
    label_singular: 'Chapter'
    folder: '_src/chapter'
    create: true
    slug: 'index'
    editor:
      preview: false
    fields:
      - { label: 'Permalink', name: 'permalink', widget: 'string', required: false }
      - { label: 'Chapter Number', name: 'chapterNumber', widget: 'number', required: false }
      - { label: 'Chapter Title', name: 'title', widget: 'string' }
      - { label: 'Order', name: 'tocOrder', widget: 'number', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
